apiVersion: tekton.dev/v1beta1
kind: Task
name: cleanup
spec.workspaces.name: source

spec:
  description: This task will clean up a workspace by deleting all the files.
  workspaces:
    - name: remove
  steps:
    - name: remove
      image: alpine:3
      env:
        - name: WORKSPACE_SOURCE_PATH
          value: $(workspaces.source.path)
      workingDir: $(workspaces.source.path)
      securityContext:
        runAsNonRoot: false
        runAsUser: 0
      script: script.sh
